version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: web
    command: sh -c "sleep 5 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=mydatabase
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DJANGO_ALLOWED_HOSTS=0.0.0.0,localhost
      - PYTHONPATH=/app/vanger

volumes:
  mysql_data: